# Generated by Django 5.2.6 on 2025-09-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("instructor", "Instructor"),
                    ("student", "Student"),
                ],
                default="student",
                help_text="User's role in the system",
                max_length=20,
            ),
        ),
    ]
