# Generated by Django 5.2.6 on 2025-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, default='', help_text="The ID of the user's OAuth account", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='oauth_provider',
            field=models.CharField(blank=True, default='', help_text="The provider of the user's OAuth account", max_length=50),
        ),
    ]
