name: CI

on:
  push:
    branches:
        - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
        - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    name: Setup
    outputs: 
      branch: ${{ steps.branch_name.outputs.current_branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

  backend:
    name: backend
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      DJANGO_SETTINGS_MODULE: adaptive_testing.settings.ci
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY || 'ci-secret-key-for-testing-only' }}
      DEBUG: false
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      # For non-PR events use a persistent secret; for PRs we'll set via Neon action
      DATABASE_URL: ${{ github.event_name != 'pull_request' && secrets.DATABASE_URL || '' }}
      PY_VERSION: '3.13.7'
    steps:
      - uses: actions/checkout@v4
      
      - name: Get branch expiration date (2 weeks from now)
        if: github.event_name == 'pull_request'
        id: get_expiration_date
        run: echo "EXPIRES_AT=$(date -u --date '+14 days' +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_ENV"
      
      - name: Create Neon Branch
        if: github.event_name == 'pull_request'
        id: create_neon_branch
        uses: neondatabase/create-branch-action@v6.1.1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
          expires_at: ${{ env.EXPIRES_AT }}
      
      - name: Set DATABASE_URL from Neon action
        if: github.event_name == 'pull_request'
        run: |
          echo "DATABASE_URL=${{ steps.create_neon_branch.outputs.db_url_pooled }}" >> "$GITHUB_ENV"
      
      - name: Export per-run test DB suffix
        run: |
          echo "DJANGO_TEST_DB_SUFFIX=${{ github.run_id }}_${{ github.run_attempt }}" >> "$GITHUB_ENV"
      
      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: venv-${{ runner.os }}-${{ env.PY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Run linting
        run: poetry run ruff check .
      - name: Run type checking
        run: poetry run mypy .
      - name: Run migrations
        run: poetry run python manage.py migrate --noinput --settings=adaptive_testing.settings.ci
      - name: Run tests
        run: poetry run pytest --cov=adaptive_testing --cov=apps --cov-report=xml --cov-report=html --ds=adaptive_testing.settings.ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage

  delete_neon_branch:
    name: Delete Neon Branch
    needs: [setup, backend]
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
            project_id: ${{ vars.NEON_PROJECT_ID }}
            branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
            api_key: ${{ secrets.NEON_API_KEY }}


  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test:run
      - name: Build
        run: npm run build

  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # GitLeaks - Secret scanning
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      
      # CodeQL - Static analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript, python
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v4
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
